theme: jekyll-theme-conference

title: "PN26"
url: "https://mromerot.github.io"
baseurl: "/programa-pn26"

conference:
  lang: es
  title: "Plataforma Nacional para la Gestión del Riesgo de Desastres 2026"
  url: "https://mromerot.github.io/programa-pn26"
  tz: "-05:00"

  navigation:
    logo:
      name: PN26
    links:
      - name: Programa
        relative_url: /program/
      - name: Sesiones
        relative_url: /talks/
      - name: Escenarios en Vivo
        relative_url: /escenarios-en-vivo/
      - name: Stands
        relative_url: /stands/
      - name: Ponentes
        relative_url: /speakers/
      - name: Instituciones
        relative_url: /instituciones/
      - name: Mapa
        relative_url: /location/

  talks:
    tracks:
      - name: Plenaria
        color: primary
      - name: "Sesión paralela"
        color: success
      - name: "Sesión temática"
        color: info
      - name: "Sesión especial"
        color: warning
      - name: Laboratorio de aprendizaje
        color: danger
      - name: Dialogos de alto nivel
        color: secondary
      - name: Ceremonias
        color: dark

  program:
    url: /program/

  schema_org:
    organizer:
      name: "Unidad Nacional para la Gestión del Riesgo de Desastres (UNGRD)"
      url: "https://portal.gestiondelriesgo.gov.co"

collections:
  talks:
    output: true
    permalink: /talks/:name/
  speakers:
    output: true
    permalink: /speakers/:name/
  rooms:
    output: true
    permalink: /rooms/:name/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room
